"""hierarquia planta-area-linha, criticidade e politica de alertas

Revision ID: 72a013b7ea06
Revises: 754af15cf28e
Create Date: 2026-08-31 12:23:29.412280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72a013b7ea06'
down_revision: Union[str, None] = '754af15cf28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_plants_code')
    )
    op.create_index(op.f('ix_plants_code'), 'plants', ['code'], unique=False)
    op.create_index(op.f('ix_plants_created_at'), 'plants', ['created_at'], unique=False)
    op.create_index(op.f('ix_plants_deleted_at'), 'plants', ['deleted_at'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id', 'code', name='uq_areas_plant_code')
    )
    op.create_index(op.f('ix_areas_created_at'), 'areas', ['created_at'], unique=False)
    op.create_index(op.f('ix_areas_deleted_at'), 'areas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_areas_plant_id'), 'areas', ['plant_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'code', name='uq_lines_area_code')
    )
    op.create_index(op.f('ix_lines_area_id'), 'lines', ['area_id'], unique=False)
    op.create_index(op.f('ix_lines_created_at'), 'lines', ['created_at'], unique=False)
    op.create_index(op.f('ix_lines_deleted_at'), 'lines', ['deleted_at'], unique=False)
    op.drop_index('ix_sectors_created_at', table_name='sectors')
    op.add_column('alerts', sa.Column('rule', sa.String(length=40), nullable=False,
                                  server_default='DEGRADACAO'))
    op.add_column('alerts', sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()),
                                  nullable=False, server_default='[]'))
    op.add_column('alerts', sa.Column('priority_score', sa.Float(), nullable=False,
                                  server_default='0'))
    op.add_column('alerts', sa.Column('fault_type', sa.String(length=20), nullable=True))
    op.add_column('alerts', sa.Column('physical_type', sa.String(length=20), nullable=True))
    op.add_column('alerts', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('evidence_agreement', sa.Boolean(), nullable=True))
    op.add_column('alerts', sa.Column('trend_pct', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('alerts', sa.Column('ml_model_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_alerts_ml_model_id'), 'alerts', ['ml_model_id'], unique=False)
    op.create_index(op.f('ix_alerts_priority_score'), 'alerts', ['priority_score'], unique=False)
    op.create_index(op.f('ix_alerts_rule'), 'alerts', ['rule'], unique=False)
    op.create_index('ix_alerts_status_priority', 'alerts', ['status', 'priority_score'], unique=False)
    op.create_foreign_key(None, 'alerts', 'ml_models', ['ml_model_id'], ['id'], ondelete='RESTRICT')
    op.add_column('motors', sa.Column('line_id', sa.UUID(), nullable=True))
    op.add_column('motors', sa.Column('criticality', sa.String(length=1), nullable=False,
                                  server_default='B'))
    op.drop_index('ix_motors_sector_id', table_name='motors')
    op.create_index(op.f('ix_motors_line_id'), 'motors', ['line_id'], unique=False)
    op.drop_constraint('motors_sector_id_fkey', 'motors', type_='foreignkey')
    op.create_foreign_key(None, 'motors', 'lines', ['line_id'], ['id'], ondelete='SET NULL')
    op.drop_column('motors', 'sector_id')
    # a tabela so pode cair depois da coluna que a referencia
    op.drop_table('sectors')
    # ### end Alembic commands ###


    # o default de 'rule' serve apenas para migrar linhas preexistentes;
    # novas linhas devem sempre informar a regra que originou o alerta
    op.alter_column('alerts', 'rule', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motors', sa.Column('sector_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'motors', type_='foreignkey')
    op.create_foreign_key('motors_sector_id_fkey', 'motors', 'sectors', ['sector_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_motors_line_id'), table_name='motors')
    op.create_index('ix_motors_sector_id', 'motors', ['sector_id'], unique=False)
    op.drop_column('motors', 'criticality')
    op.drop_column('motors', 'line_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index('ix_alerts_status_priority', table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priority_score'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ml_model_id'), table_name='alerts')
    op.drop_column('alerts', 'ml_model_id')
    op.drop_column('alerts', 'indicators')
    op.drop_column('alerts', 'trend_pct')
    op.drop_column('alerts', 'evidence_agreement')
    op.drop_column('alerts', 'confidence')
    op.drop_column('alerts', 'physical_type')
    op.drop_column('alerts', 'fault_type')
    op.drop_column('alerts', 'priority_score')
    op.drop_column('alerts', 'reasons')
    op.drop_column('alerts', 'rule')
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sectors_pkey'),
    sa.UniqueConstraint('name', name='sectors_name_key')
    )
    op.create_index('ix_sectors_created_at', 'sectors', ['created_at'], unique=False)
    op.drop_index(op.f('ix_lines_deleted_at'), table_name='lines')
    op.drop_index(op.f('ix_lines_created_at'), table_name='lines')
    op.drop_index(op.f('ix_lines_area_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_areas_plant_id'), table_name='areas')
    op.drop_index(op.f('ix_areas_deleted_at'), table_name='areas')
    op.drop_index(op.f('ix_areas_created_at'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_plants_deleted_at'), table_name='plants')
    op.drop_index(op.f('ix_plants_created_at'), table_name='plants')
    op.drop_index(op.f('ix_plants_code'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
