"""severidade por criterio fisico como saida primaria

Revision ID: 747aed093186
Revises: 72a013b7ea06
Create Date: 2026-08-31 17:06:10.669383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '747aed093186'
down_revision: Union[str, None] = '72a013b7ea06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'priority_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('motors', 'criticality',
               existing_type=sa.VARCHAR(length=1),
               server_default=None,
               existing_nullable=False)
    op.add_column('predictions', sa.Column('severity_criterion', sa.String(length=30), nullable=True))
    op.add_column('predictions', sa.Column('severity_explanation', sa.Text(), nullable=True))
    op.add_column('predictions', sa.Column('ratio_to_baseline', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('ml_severity', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'ml_severity')
    op.drop_column('predictions', 'ratio_to_baseline')
    op.drop_column('predictions', 'severity_explanation')
    op.drop_column('predictions', 'severity_criterion')
    op.alter_column('motors', 'criticality',
               existing_type=sa.VARCHAR(length=1),
               server_default=sa.text("'B'::character varying"),
               existing_nullable=False)
    op.alter_column('alerts', 'priority_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('alerts', 'reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    # ### end Alembic commands ###
