"""tipo de fundacao para classificacao ISO

Revision ID: 7a6a5d1822db
Revises: 747aed093186
Create Date: 2026-08-31 18:07:38.895550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6a5d1822db'
down_revision: Union[str, None] = '747aed093186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motors', sa.Column('foundation_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motors', 'foundation_type')
    # ### end Alembic commands ###
