"""schema inicial: motores, medicoes, previsoes, ml_models, alertas

Revision ID: fb0138391f6b
Revises: 
Create Date: 2026-08-31 11:06:09.305857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0138391f6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('algorithm', sa.String(length=80), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('n_windows', sa.Integer(), nullable=True),
    sa.Column('n_features', sa.Integer(), nullable=True),
    sa.Column('window_seconds', sa.Float(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('known_limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_created_at'), 'ml_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_models_is_active'), 'ml_models', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_models_version'), 'ml_models', ['version'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sectors_created_at'), 'sectors', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'MANUTENCAO', 'OPERADOR')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('motors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('power_kw', sa.Float(), nullable=True),
    sa.Column('rated_rpm', sa.Integer(), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('rated_current_a', sa.Float(), nullable=True),
    sa.Column('rated_voltage_v', sa.Float(), nullable=True),
    sa.Column('iso_machine_class', sa.String(length=4), nullable=False),
    sa.Column('baseline_measurement_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_measurement_id'], ['measurements.id'], name='fk_motors_baseline_measurement', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag', name='uq_motors_tag')
    )
    op.create_index(op.f('ix_motors_created_at'), 'motors', ['created_at'], unique=False)
    op.create_index(op.f('ix_motors_deleted_at'), 'motors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_motors_sector_id'), 'motors', ['sector_id'], unique=False)
    op.create_index(op.f('ix_motors_tag'), 'motors', ['tag'], unique=False)
    op.create_table('maintenances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maintenance_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_created_at'), 'maintenances', ['created_at'], unique=False)
    op.create_index(op.f('ix_maintenances_motor_id'), 'maintenances', ['motor_id'], unique=False)
    op.create_index(op.f('ix_maintenances_performed_at'), 'maintenances', ['performed_at'], unique=False)
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_nm', sa.Float(), nullable=True),
    sa.Column('rpm', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('operating_hours', sa.Float(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('sample_rate_hz', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_channels', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iso_v_rms_mms', sa.Float(), nullable=True),
    sa.Column('iso_v_1x_mms', sa.Float(), nullable=True),
    sa.Column('iso_v_2x_mms', sa.Float(), nullable=True),
    sa.Column('iso_a_hf_g', sa.Float(), nullable=True),
    sa.Column('iso_zone', sa.String(length=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('n_channels > 0', name='ck_measurements_channels'),
    sa.CheckConstraint('sample_rate_hz > 0', name='ck_measurements_sample_rate'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_collected_at'), 'measurements', ['collected_at'], unique=False)
    op.create_index(op.f('ix_measurements_created_at'), 'measurements', ['created_at'], unique=False)
    op.create_index('ix_measurements_motor_created', 'measurements', ['motor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_measurements_motor_id'), 'measurements', ['motor_id'], unique=False)
    op.create_index(op.f('ix_measurements_source_sha256'), 'measurements', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_measurements_user_id'), 'measurements', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('measurement_id', sa.UUID(), nullable=False),
    sa.Column('ml_model_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('severity_probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fault_type', sa.String(length=20), nullable=False),
    sa.Column('fault_type_probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('physical_type', sa.String(length=20), nullable=True),
    sa.Column('evidence_agreement', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('baseline_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inference_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fault_type IN ('normal', 'bearing', 'misalignment', 'unbalance')", name='ck_predictions_fault_type'),
    sa.CheckConstraint("severity IN ('HEALTHY', 'WARNING', 'FAILURE')", name='ck_predictions_severity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_predictions_confidence'),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ml_model_id'], ['ml_models.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_fault_type'), 'predictions', ['fault_type'], unique=False)
    op.create_index(op.f('ix_predictions_measurement_id'), 'predictions', ['measurement_id'], unique=True)
    op.create_index(op.f('ix_predictions_ml_model_id'), 'predictions', ['ml_model_id'], unique=False)
    op.create_index(op.f('ix_predictions_severity'), 'predictions', ['severity'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motor_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('WARNING', 'FAILURE')", name='ck_alerts_severity'),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')", name='ck_alerts_status'),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_motor_id'), 'alerts', ['motor_id'], unique=False)
    op.create_index('ix_alerts_motor_status', 'alerts', ['motor_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_prediction_id'), 'alerts', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('motor_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('confirmed_fault_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_motor_id'), 'inspections', ['motor_id'], unique=False)
    op.create_index(op.f('ix_inspections_performed_at'), 'inspections', ['performed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspections_performed_at'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_motor_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_prediction_id'), table_name='alerts')
    op.drop_index('ix_alerts_motor_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_motor_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_severity'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_ml_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_measurement_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_fault_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_measurements_user_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_source_sha256'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_motor_id'), table_name='measurements')
    op.drop_index('ix_measurements_motor_created', table_name='measurements')
    op.drop_index(op.f('ix_measurements_created_at'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_collected_at'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_maintenances_performed_at'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_motor_id'), table_name='maintenances')
    op.drop_index(op.f('ix_maintenances_created_at'), table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index(op.f('ix_motors_tag'), table_name='motors')
    op.drop_index(op.f('ix_motors_sector_id'), table_name='motors')
    op.drop_index(op.f('ix_motors_deleted_at'), table_name='motors')
    op.drop_index(op.f('ix_motors_created_at'), table_name='motors')
    op.drop_table('motors')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sectors_created_at'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_ml_models_version'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_is_active'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_created_at'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
